input_size: [256, 512]
input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

custom_module_paths: ["layers"]
backbone:
    [
        [-1, 1,  nn.Conv2d,[32,7,1,3],{bias: False}],
        [-1, 1,  BDNblockCSP,[32,7,16,0.5,1,True,True,True]],
        [-1, 1,  nn.Conv2d,[64,3,2,1 ],{ bias: False }],
        [-1, 1,  BDNblockCSP,[64,15,16,0.5,1,True,True,True]],
        [-1, 1,  nn.Conv2d,[128,3,2,1 ],{ bias: False }],
        [-1, 1,  BDNblockCSP,[128,21,16,0.5,1,True,True,True]],
        [-1, 1,  nn.Conv2d,[256,3,2,1 ],{ bias: False }],
        [-1, 1,  BDNblockCSP,[256,1,16,0.5,9,False,False,True]],
        [-1, 1,  nn.Conv2d,[512,3,2,1 ],{ bias: False }],
        [-1, 1,  BDNblockCSP,[512,1,16,0.5,18,False,False,True]],
        [[9,7], 1, UpsampleBlock,[256,"cat"]],
        [[7,5], 1, UpsampleBlock,[128,"cat"]],
        [[5,3], 1, UpsampleBlock,[64,"cat"]],
        [[3,1], 1, UpsampleBlock,[32,"cat"]],
        [[10,11], 1, UpsampleBlock,[128,"cat"]],
        [[11,12], 1, UpsampleBlock,[64,"cat"]],
        [[12,13], 1, UpsampleBlock,[32,"cat"]],
        [[14,15], 1, UpsampleBlock,[64,"cat"]],
        [[15,16], 1, UpsampleBlock,[32,"cat"]],
        [[17,18], 1, UpsampleBlock,[32,"cat"]],
        [19, 1, Head, [1,16,1]],
        [19, 1, Head, [3,16,1]],
        [19, 1, Head, [21,16,1]]
    ]
